### ISSUE TITLE
License considerations

### ISSUE THREAD

**Issue by TechnologyClassroom** [cr4yfish/nemmy#27]
I see you have a custom license for this project.

I would suggest releasing the code under the AGPL-3.0-or-later license like Lemmy.

**Comment by cr4yfish** [comment]
Yeah, I'll take a look at that.

I only used a custom license because I have no clue about Licenses :).

**Comment by TechnologyClassroom** [comment]
Custom licenses are tricky because if anyone wants to use the project, they might need a lawyer to determine which items are compatible with other licenses, which are not enforceable, etc. Whereas there are already licenses that hold up in court that have known compatibilities with other licenses.

As the number of contributors grow, the ability to change a license becomes harder as well. It is good to standardize as soon as possible in my opinion.

AGPL (the license that Lemmy picked) is one of the best and my favorite.

**Comment by TechnologyClassroom** [comment]
Thank you!
