### ISSUE TITLE
website 402 (vercel billing issue)

### ISSUE THREAD

**Issue by dym-sohin** [cr4yfish/nemmy#58]
**Describe the bug**
main website outgrew the free tier

**To Reproduce**
visit https://nemmy.app/

![screenshot](https://github.com/cr4yfish/nemmy/assets/140316503/c6242f23-44e5-4150-a333-76b54304f842)

```
This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

402: PAYMENT_REQUIRED Code: DEPLOYMENT_DISABLED ID: fra1::9ctrc-1696275296111-a411027385bf

    If you are a visitor, contact the website owner or try again later.
    If you are the owner, please [read this documentation section](https://vercel.com/docs/errors/platform-error-codes#deployment_disabled).
```

**Comment by cr4yfish** [comment]
Yeah I'm not sure how to solve that. Initially I thought I have to wait for the next billing period but as it seems my whole Vercel account is being held "hostage".

I don't have the funds to pay 20€/month for a pro vercel account so I'd have to search for another free hosting provider that's as good as vercel.

The whole situation has caused me to lose all motivation for web-projects, so there won't be any updates until I get some motivation to move all of my projects somewhere else.

**Comment by dym-sohin** [comment]
20$/month per project?! yeah that's just bullshit

redhat-openshift has a free plan, you can try that

but in the long term, having some old-school server w/o per-use micro-transactions crap would be so much simpler with a little bit of docker and nginx

sorry for sounding like a salesman (that's b/c i went through multitude of VPS hosters and landed here myself),
but i would recommend ssdnodes for lowest price, best stats, and ideal uptime
(starting for 50$/**year** — 8GB / 240GB / 2x core / 4TB Transfer) — this will be sufficient for at least a _dozen_ of regular-sized low-traffic projects.

also, since you already paying for domain, temporary redirect to a git-repo is like a standard solution, to at least keep things discoverable

**Comment by cr4yfish** [comment]
Thanks for all that info! I will definitely take a look at ssdnodes.

Temporarily, I will upload Nemmy to a free Netlify server because I need it tomorrow and the setup is quick (show-and-tell in a university class).


P.S.
It's 20$/member of a "team" on Vercel, so basically 20$/month for the whole account and all the usage limits are shared across projects - still much too expensive. A pay-as-you-go model would be much nicer for hobby-projects.
